Traceback (most recent call last):
  File "/home/shq19004/Code/geeget/batch/batch_download.py", line 66, in <module>
    main()
  File "/home/shq19004/miniconda3/envs/nightlight/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/shq19004/miniconda3/envs/nightlight/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/shq19004/miniconda3/envs/nightlight/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shq19004/miniconda3/envs/nightlight/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/shq19004/Code/geeget/batch/batch_download.py", line 54, in main
    gd.hls(destination,
  File "/home/shq19004/Code/geeget/download/download.py", line 188, in hls
    os.remove(filepath_reference)
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/sharedfs1/zhulab/Shi/ProjectSythetic/Test/SERC/reference_layer.tif'
slurmstepd: error: *** JOB 11725291 ON cn510 CANCELLED AT 2025-01-12T17:13:25 ***
